version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mssql:
  #   image: mcr.microsoft.com/mssql/server:2019-latest
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: ${MSSQL_PASSWORD}
  #     MSSQL_PID: Express
  #   ports:
  #     - "${MSSQL_PORT}:1433"
  #   volumes:
  #     - mssql_data:/var/opt/mssql

volumes:
  postgres_data:
  mssql_data: 